import type { AuditPaper } from '@/lib/services/publications/audit-import'

// Transcribed from the validated audit inventory (Gmail solenn.toupin, janv.->juil. 2026).
// Every ambiguity encountered during transcription is recorded in the paper's `notes` field
// rather than guessed. See /private/tmp/.../scratchpad/audit-inventory.md for the source.

export const AUDIT_PAPERS: AuditPaper[] = [
  // #1 - HCM-LGE Risk Score (mortalite, CMH) - ACCEPTED - corresp. Florence
  {
    title: 'Cardiovascular Magnetic Resonance Late Gadolinium Enhancement Risk Score for Mortality in Patients with Hypertrophic Cardiomyopathy: the HCM-LGE Risk Score',
    articleStatus: 'ACCEPTED',
    authors: [
      { name: 'Jeremy Florence', isCorresponding: true },
      { name: 'Jerome Garot' },
      { name: 'Alexandre Unger' },
      { name: 'Solenn Toupin' },
      { name: 'Suzanne Duhamel' },
      { name: 'Francesca Sanguineti' },
      { name: 'Mariama Akodad' },
      { name: 'Thomas Hovasse' },
      { name: 'Stephane Champagne' },
      { name: 'Thierry Unterseeh' },
      { name: 'Antoinette Neylon' },
      { name: 'Alexis Hermida' },
      { name: 'Nicolas Martin' },
      { name: 'Julien Hudelo' },
      { name: 'Trecy Goncalves' },
      { name: 'Aicha Kante' },
      { name: 'Antoine Lequipar' },
      { name: 'Jean-Guillaume Dillinger' },
      { name: 'Valerie Bousson' },
      { name: 'Philippe Garot' },
      { name: 'Yohann Bohbot' },
      { name: 'Theo Pezel' },
    ],
    submissions: [
      { journalName: 'European Heart Journal - Cardiovascular Imaging', submittedAt: '2026-01-01', status: 'REJECTED' },
      { journalName: 'Circulation: Cardiovascular Imaging', submittedAt: '2026-05-27', status: 'REJECTED' },
      { journalName: 'Radiology', submittedAt: '2026-07-01', status: 'ACCEPTED' },
    ],
    notes:
      'Manuscript IDs: Circ CVI 020107, Radiology RAD-26-2008. EHJ-CVI submission date only known to the month (Jan 2026) — used the 1st as a placeholder.',
  },

  // #2 - Midwall LGE Presence/Location/Extent, Ischemic CM - TO_RESUBMIT (decision JMRI) - corresp. Unger
  {
    title: 'Prognostic Value of Midwall Late Gadolinium Enhancement Presence, Location and Extent in Patient with Ischemic Cardiomyopathy',
    articleStatus: 'TO_RESUBMIT',
    authors: [
      { name: 'Alexandre Unger', isCorresponding: true },
      { name: 'Jerome Garot' },
      { name: 'Philippe Garot' },
      { name: 'Suzanne Duhamel' },
      { name: 'Francesca Sanguineti' },
      { name: 'Mariama Akodad' },
      { name: 'Antoinette Neylon' },
      { name: 'Thomas Hovasse' },
      { name: 'Bernard Chevalier' },
      { name: 'Stephane Champagne' },
      { name: 'Thierry Unterseeh' },
      { name: 'Lounis Hamzi' },
      { name: 'Trecy Goncalves' },
      { name: 'Edouard Ballout' },
      { name: 'Jeremy Florence' },
      { name: 'Emmanuel Gall' },
      { name: 'Paul-jun Martial' },
      { name: 'Andreea Afana' },
      { name: 'Aicha Kante' },
      { name: 'Alexandre Pfeffer' },
      { name: 'Antoine Lequipar' },
      { name: 'Jean-Guillaume Dillinger' },
      { name: 'Patrick Henry' },
      { name: 'Antoine Bondue' },
      { name: 'Valerie Bousson' },
      { name: 'Solenn Toupin' },
      { name: 'Theo Pezel' },
    ],
    submissions: [
      { journalName: 'Journal of Cardiovascular Magnetic Resonance', submittedAt: '2026-02-12', status: 'REJECTED' },
      { journalName: 'Circulation: Cardiovascular Imaging', submittedAt: '2026-04-22', status: 'REJECTED' },
      { journalName: 'European Radiology', submittedAt: '2026-06-03', status: 'REJECTED' },
      { journalName: 'Journal of Magnetic Resonance Imaging', submittedAt: '2026-07-07', status: 'MAJOR_REVISIONS' },
    ],
    notes:
      'Manuscript IDs: Circ CVI 019980, Eur Radiology EURA-02815, JMRI 1338. Current status is TO_RESUBMIT following the JMRI decision; wording did not specify minor vs major, MAJOR_REVISIONS used per default rule.',
  },

  // #3 - Midwall LGE Granularity, Ischaemic CM - UNDER_REVIEW - corresp. Garot (author list unavailable)
  {
    title: 'Prognostic Value of Cardiovascular Magnetic Resonance Midwall Late Gadolinium Enhancement Granularity in Ischaemic Cardiomyopathy',
    articleStatus: 'UNDER_REVIEW',
    authors: [{ name: 'Jerome Garot', isCorresponding: true }],
    submissions: [{ journalName: 'European Heart Journal - Cardiovascular Imaging', submittedAt: '2026-01-01', status: 'UNDER_REVIEW' }],
    notes:
      'Manuscript ID EHJCI-00224. Full author list unavailable — the EHJ-CVI submission email did not list co-authors; only the corresponding author (Jerome Garot) is known. Submission date only known to the month (Jan 2026) — used the 1st as a placeholder.',
  },

  // #4 - LGE Granularity in HCM (incremental) - UNDER_REVIEW - corresp. Garot
  {
    title: 'Incremental Prognostic Value of Cardiovascular Magnetic Resonance Late Gadolinium Enhancement Granularity in Hypertrophic Cardiomyopathy',
    articleStatus: 'UNDER_REVIEW',
    authors: [
      { name: 'Jeremy Florence' },
      { name: 'Philippe Garot' },
      { name: 'Solenn Toupin' },
      { name: 'Francesca Sanguineti' },
      { name: 'Suzanne Duhamel' },
      { name: 'Trecy Goncalves' },
      { name: 'Alexandre Unger' },
      { name: 'Emmanuel Gall' },
      { name: 'Edouard Ballout' },
      { name: 'Paul-Jun Martial' },
      { name: 'Raphael Mirailles' },
      { name: 'Alexandre Pfeffer' },
      { name: 'Manveer Singh' },
      { name: 'Claire Baladi' },
      { name: 'Jean-Guillaume Dillinger' },
      { name: 'Patrick Henry' },
      { name: 'Valerie Bousson' },
      { name: 'Thomas Hovasse' },
      { name: 'Stephane Champagne' },
      { name: 'Thierry Unterseeh' },
      { name: 'Myriam Akodad' },
      { name: 'Antoinette Neylon' },
      { name: 'Yohann Bohbot' },
      { name: 'Guillaume Clerfond' },
      { name: 'Romain Eschalier' },
      { name: 'Theo Pezel' },
      { name: 'Jerome Garot', isCorresponding: true },
    ],
    submissions: [
      { journalName: 'European Heart Journal - Cardiovascular Imaging', submittedAt: '2026-04-30', status: 'REJECTED' },
      { journalName: 'Journal of Cardiovascular Magnetic Resonance', submittedAt: '2026-05-22', status: 'UNDER_REVIEW' },
    ],
    notes: 'Manuscript ID JOFCMR-00253.',
  },

  // #5 - Stress CMR / Active Cancer (propensity) - UNDER_REVIEW - corresp. Garot
  {
    title: 'Prognostic Implications of Stress CMR in Patients with Active Cancer: A Propensity Score-Matched Cohort Study',
    articleStatus: 'UNDER_REVIEW',
    authors: [
      { name: 'Andreea Sorina Afana' },
      { name: 'Suzanne Duhamel' },
      { name: 'Solenn Toupin' },
      { name: 'Francesca Sanguineti' },
      { name: 'Thomas Hovasse' },
      { name: 'Philippe Garot' },
      { name: 'Benjamin Sibilia' },
      { name: 'Theo Pezel' },
      { name: 'Jerome Garot', isCorresponding: true },
      { name: 'Trecy Goncalves' },
    ],
    submissions: [
      { journalName: 'JACC: CardioOncology', submittedAt: '2026-01-01', status: 'REJECTED' },
      { journalName: 'European Radiology', submittedAt: '2026-06-02', status: 'REJECTED' },
      { journalName: 'Radiology: Cardiothoracic Imaging', submittedAt: '2026-06-23', status: 'UNDER_REVIEW' },
    ],
    notes:
      'Manuscript IDs: JACC:CardioOncology JCO050126-0477, Eur Radiology EURA-02791, Radiology: CTI RYCT-0291. No date at all was given for the JACC:CardioOncology submission in the audit source — 2026-01-01 used as an unverified placeholder (must precede the 2-juin Eur Radiology submission); verify manually.',
  },

  // #6 - ML mortalite 5-ans post-STEMI (FAST-MI) - UNDER_REVIEW - corresp. Pezel (author order to confirm)
  {
    title: 'Machine learning models for prediction of 5-year all-cause mortality after hospital discharge following ST-elevation myocardial infarction: insight from the FAST-MI registries',
    articleStatus: 'UNDER_REVIEW',
    authors: [
      { name: 'Manveer Singh' },
      { name: 'Emmanuel Gall' },
      { name: 'Kenza Hamzi' },
      { name: 'Solenn Toupin' },
      { name: 'Trecy Goncalves' },
      { name: 'Jean-Guillaume Dillinger' },
      { name: 'Patrick Henry' },
      { name: 'Charles Fauvel' },
      { name: 'Antonin Trimaille' },
      { name: 'Nefissa Hammache' },
      { name: 'Thibaut Pommier' },
      { name: 'Guillaume Cayla' },
      { name: 'Francois Schiele' },
      { name: 'Jean Ferrieres' },
      { name: 'Tabassome Simon' },
      { name: 'Nicolas Danchin' },
      { name: 'Theo Pezel', isCorresponding: true },
    ],
    submissions: [{ journalName: 'European Heart Journal', submittedAt: '2026-06-01', status: 'UNDER_REVIEW' }],
    notes:
      'Manuscript ID EURHEARTJ-02759. Submission date only known to the month (juin 2026) — used the 1st as a placeholder. Author order was reconstructed from an email header and is unconfirmed.',
  },

  // #7 - ML asymptomatic CAD, 10-yr FU - UNDER_REVIEW - corresp. Pezel
  {
    title: 'Machine learning-based prediction of cardiovascular events using stress cardiovascular magnetic resonance in asymptomatic patients with known CAD: a multicentre study with 10-year follow-up',
    articleStatus: 'UNDER_REVIEW',
    authors: [
      { name: 'Jonas Amar' },
      { name: 'Trecy Goncalves' },
      { name: 'Suzanne Duhamel' },
      { name: 'Mariama Akodad' },
      { name: 'Thomas Hovasse' },
      { name: 'Antoinette Neylon' },
      { name: 'Stephane Champagne' },
      { name: 'Thierry Unterseeh' },
      { name: 'Alexandre Unger' },
      { name: 'Jeremy Florence' },
      { name: 'Sonia Houssany' },
      { name: 'Julien Hudelo' },
      { name: 'Jean-Guillaume Dillinger' },
      { name: 'Valerie Bousson' },
      { name: 'Francesca Sanguineti' },
      { name: 'Philippe Garot' },
      { name: 'Jerome Garot' },
      { name: 'Solenn Toupin' },
      { name: 'Theo Pezel', isCorresponding: true },
    ],
    submissions: [{ journalName: 'European Heart Journal - Digital Health', submittedAt: '2026-05-31', status: 'UNDER_REVIEW' }],
    notes: 'Manuscript ID EHJ-DH-00337.',
  },

  // #8 - MIRACL.ai Design Blueprint (State-of-the-Art review) - UNDER_REVIEW - corresp. Pezel
  {
    title: 'MIRACL.ai Design Blueprint for a Centralized Multimodality Cardiovascular Imaging Core Laboratory and Artificial Intelligence: A State-of-the-Art Review',
    articleStatus: 'UNDER_REVIEW',
    authors: [
      { name: 'Solenn Toupin' },
      { name: 'Jean-Nicolas Dacher' },
      { name: 'Augustin Coisne' },
      { name: 'Marine Beaumont' },
      { name: 'Francois Pontana' },
      { name: 'Yohann Bohbot' },
      { name: 'Elie Mousseaux' },
      { name: 'Jerome Garot' },
      { name: 'Beatrice Daoud' },
      { name: 'Olivier Huttin' },
      { name: 'Cedric Renard' },
      { name: 'Charles Fauvel' },
      { name: 'Valerie Bousson' },
      { name: 'Christian De Chillou' },
      { name: 'Paul-Jun Martial' },
      { name: 'Jean-Guillaume Dillinger' },
      { name: 'Trecy Goncalves' },
      { name: 'Jean-Sebastien Hulot' },
      { name: 'Fabien Hyafil' },
      { name: 'Eric Vicaut' },
      { name: 'Gilles Soulat' },
      { name: 'Theo Pezel', isCorresponding: true },
    ],
    submissions: [{ journalName: 'Archives of Cardiovascular Diseases', submittedAt: '2026-07-02', status: 'UNDER_REVIEW' }],
  },

  // #9 - ML seuil semi-quant LGE & mortalite (HCM) - UNDER_REVIEW - corresp. Pezel
  {
    title: 'Machine Learning-Derived Semi-quantitative Late Gadolinium Enhancement Threshold and All-Cause Mortality in Hypertrophic Cardiomyopathy: Multicentre Derivation and External Validation',
    articleStatus: 'UNDER_REVIEW',
    authors: [
      { name: 'Jeremy Florence' },
      { name: 'Jerome Garot' },
      { name: 'Solenn Toupin' },
      { name: 'Suzanne Duhamel' },
      { name: 'Charles Fauvel' },
      { name: 'Jean-Nicolas Dacher' },
      { name: 'Philippe Garot' },
      { name: 'Francesca Sanguineti' },
      { name: 'Thomas Hovasse' },
      { name: 'Mariama Akodad' },
      { name: 'Antoinette Neylon' },
      { name: 'Julien Hudelo' },
      { name: 'Paul-Jun Martial' },
      { name: 'Aicha Kante' },
      { name: 'Trecy Goncalves' },
      { name: 'Giulia Nardoianni' },
      { name: 'Malak Benabdellah' },
      { name: 'Jean-Guillaume Dillinger' },
      { name: 'Christophe Tribouilloy' },
      { name: 'Alexis Hermida' },
      { name: 'Valerie Bousson' },
      { name: 'Yohann Bohbot' },
      { name: 'Theo Pezel', isCorresponding: true },
    ],
    submissions: [{ journalName: 'Archives of Cardiovascular Diseases', submittedAt: '2026-06-30', status: 'UNDER_REVIEW' }],
  },

  // #10 - Sex diff / Acute Myocarditis (LV recovery) - UNDER_REVIEW - corresp. unclear
  {
    title: 'Sex Differences in Outcomes and Left Ventricular Recovery After Acute Myocarditis Despite Comparable Late Gadolinium Enhancement: A Multicenter Cohort Study',
    articleStatus: 'UNDER_REVIEW',
    authors: [{ name: 'Simon Viscogliosi', isCorresponding: true }],
    submissions: [{ journalName: 'European Journal of Heart Failure', submittedAt: '2026-06-22', status: 'UNDER_REVIEW' }],
    notes:
      'Manuscript ID EURJHF-931. Corresponding author is unclear in the audit source (marked "?"). Simon Viscogliosi is the probable first author, used here as a placeholder corresponding author. Remaining co-authors are known only as an unordered pool (not transcribed pending confirmation of order): Bohbot, Hudelo, Fauvel, Dacher, Bousson, Goncalves, Florence, Toupin, Pezel.',
  },

  // #11 - Coronary revasc + CMR viability - UNDER_REVIEW - corresp. Garot
  {
    title: 'Impact of coronary revascularization in patients undergoing cardiovascular magnetic resonance for viability assessment',
    articleStatus: 'UNDER_REVIEW',
    authors: [
      { name: 'Antoine Lequipar' },
      { name: 'Alexandre Unger' },
      { name: 'Suzanne Duhamel' },
      { name: 'Philippe Garot' },
      { name: 'Solenn Toupin' },
      { name: 'Francesca Sanguineti' },
      { name: 'Thomas Hovasse' },
      { name: 'Antoinette Neylon' },
      { name: 'Myriam Akodad' },
      { name: 'Stephane Champagne' },
      { name: 'Thierry Unterseeh' },
      { name: 'Trecy Goncalves' },
      { name: 'Emmanuel Gall' },
      { name: 'Aicha Kante' },
      { name: 'Julien Hudelo' },
      { name: 'Valerie Bousson' },
      { name: 'Jean-Guillaume Dillinger' },
      { name: 'Patrick Henry' },
      { name: 'Theo Pezel' },
      { name: 'Jerome Garot', isCorresponding: true },
    ],
    submissions: [
      { journalName: 'Diagnostic and Interventional Imaging', submittedAt: '2026-01-04', status: 'REJECTED' },
      { journalName: 'Journal of Cardiovascular Magnetic Resonance', submittedAt: '2026-02-01', status: 'REJECTED' },
      { journalName: 'European Radiology', submittedAt: '2026-05-03', status: 'UNDER_REVIEW' },
    ],
    notes: 'Manuscript ID Eur Radiology EURA-02233.',
  },

  // #12 - Coronary revasc + stress CMR, primary prevention - UNDER_REVIEW - corresp. Garot
  {
    title: 'Impact of coronary revascularisation in patients undergoing stress cardiovascular magnetic resonance imaging in primary prevention',
    articleStatus: 'UNDER_REVIEW',
    authors: [
      { name: 'Antoine Lequipar' },
      { name: 'Jerome Garot', isCorresponding: true },
      { name: 'Suzanne Duhamel' },
      { name: 'Philippe Garot' },
      { name: 'Francesca Sanguineti' },
      { name: 'Thomas Hovasse' },
      { name: 'Stephane Champagne' },
      { name: 'Thierry Unterseeh' },
      { name: 'Bernard Chevalier' },
      { name: 'Myriam Akodad' },
      { name: 'Antoinette Neylon' },
      { name: 'Neila Sayah' },
      { name: 'Alexandre Unger' },
      { name: 'Emmanuel Gall' },
      { name: 'Alexandre Pfeffer' },
      { name: 'Elsa Richard de Vesvrotte' },
      { name: 'Julien Hudelo' },
      { name: 'Claire Baladi' },
      { name: 'Valerie Bousson' },
      { name: 'Jean-Guillaume Dillinger' },
      { name: 'Patrick Henry' },
      { name: 'Solenn Toupin' },
      { name: 'Theo Pezel' },
      { name: 'Trecy Goncalves' },
    ],
    submissions: [
      { journalName: 'Diagnostic and Interventional Imaging', submittedAt: '2026-01-08', status: 'REJECTED' },
      { journalName: 'Cardiovascular Intervention and Therapeutics', submittedAt: '2026-05-15', status: 'REJECTED' },
      { journalName: 'European Journal of Radiology', submittedAt: '2026-06-22', status: 'UNDER_REVIEW' },
    ],
    notes:
      'The second submission journal is Cardiovascular Intervention and Therapeutics, manuscript ID CVIT-D-26-00241.',
  },

  // #13 - Long-term stress CMR / Hypertension - ACCEPTED (EHJ-CVI ~6-juin) - corresp. Garot (= ex-#25 Houssany)
  {
    title: 'Long-term Prognostic Value of Stress Cardiovascular Magnetic Resonance in Patients with Hypertension without coronary artery disease',
    articleStatus: 'ACCEPTED',
    authors: [
      { name: 'Sonia Houssany-Pissot' },
      { name: 'Suzanne Duhamel' },
      { name: 'Solenn Toupin' },
      { name: 'Alexandre Unger' },
      { name: 'Francesca Sanguineti' },
      { name: 'Stephane Champagne' },
      { name: 'Thierry Unterseeh' },
      { name: 'Bernard Chevalier' },
      { name: 'Jeremy Florence' },
      { name: 'Trecy Goncalves' },
      { name: 'Nefissa Hamache' },
      { name: 'Aicha Kante' },
      { name: 'Julien Hudelo' },
      { name: 'Valerie Bousson' },
      { name: 'Jean-Guillaume Dillinger' },
      { name: 'Patrick Henry' },
      { name: 'Antoinette Neylon' },
      { name: 'Mariama Akodad' },
      { name: 'Thomas Hovasse' },
      { name: 'Jerome Garot', isCorresponding: true },
      { name: 'Theo Pezel' },
    ],
    submissions: [
      { journalName: 'Journal of Cardiovascular Magnetic Resonance', submittedAt: '2026-01-13', status: 'REJECTED' },
      { journalName: 'European Heart Journal - Cardiovascular Imaging', submittedAt: '2026-06-06', status: 'ACCEPTED' },
    ],
    notes:
      'Manuscript IDs: JCMR JOFCMR-00499, EHJ-CVI EHJCI-00589 R2. Per validated audit decision #5, corresponding author is Jerome Garot (not Philippe Garot as literally listed in one source entry) and first author is Sonia Houssany-Pissot; the author-list entry originally read "Philippe Garot (corr = Jerome Garot)" and was corrected accordingly. EHJ-CVI acceptance date only given as approximate ("~6-juin") — 2026-06-06 used.',
  },

  // #14 - Prognostic LGE / Isolated LV Dilatation & DCM - UNDER_REVIEW - corresp. Garot
  {
    title: 'Prognostic Value of Late Gadolinium Enhancement Findings in Isolated Left Ventricular Dilatation and Dilated Cardiomyopathy',
    articleStatus: 'UNDER_REVIEW',
    authors: [
      { name: 'Trecy Goncalves' },
      { name: 'Suzanne Duhamel' },
      { name: 'Solenn Toupin' },
      { name: 'Francesca Sanguineti' },
      { name: 'Philippe Garot' },
      { name: 'Thierry Unterseeh' },
      { name: 'Thomas Hovasse' },
      { name: 'Mariama Akodad' },
      { name: 'Stephane Champagne' },
      { name: 'Bernard Chevalier' },
      { name: 'Antoinette Neylon' },
      { name: 'Emmanuel Gall' },
      { name: 'Paul-jun Martial' },
      { name: 'Edouard Ballout' },
      { name: 'Raphael Mirailles' },
      { name: 'Benjamin Sibilia' },
      { name: 'Alexandre Unger' },
      { name: 'Antoine Bondue' },
      { name: 'Jeremy Florence' },
      { name: 'Jean-Guillaume Dillinger' },
      { name: 'Patrick Henry' },
      { name: 'Valerie Bousson' },
      { name: 'Jerome Garot', isCorresponding: true },
      { name: 'Theo Pezel' },
    ],
    submissions: [
      { journalName: 'European Heart Journal - Cardiovascular Imaging', submittedAt: '2026-02-14', status: 'REJECTED' },
      { journalName: 'Circulation: Cardiovascular Imaging', submittedAt: '2026-03-04', status: 'REJECTED' },
      { journalName: 'Journal of Cardiovascular Magnetic Resonance', submittedAt: '2026-03-18', status: 'UNDER_REVIEW' },
    ],
    notes: 'Manuscript ID Circ CVI 019780.',
  },

  // #15 - Post-Transplant Cyclophosphamide Cardiotoxicity, Allo-SCT - TO_RESUBMIT (R1) - corresp. Goncalves
  {
    title: 'Risk of Post-Transplant Cyclophosphamide-Related Cardiotoxicity in Allogeneic Stem Cell Transplantation',
    articleStatus: 'TO_RESUBMIT',
    authors: [
      { name: 'Trecy Goncalves', isCorresponding: true },
      { name: 'Rayane Hadjali' },
      { name: 'Florian Chevillon' },
      { name: 'Benjamin Sibilia' },
      { name: 'Theo Pezel' },
      { name: 'Solenn Toupin' },
      { name: 'Nathalie Dhedin' },
      { name: 'Lin-Pierre Zhao' },
      { name: 'Mathilde Baudet' },
      { name: 'Michael Benayoun' },
      { name: 'Matthieu Jestin' },
      { name: 'Nicolas Boissel' },
      { name: 'Alexandre Unger' },
      { name: 'Flore Sicre de Fontbrune' },
      { name: 'David Michonneau' },
      { name: 'Alienor Xhaard' },
      { name: 'Regis Peffault de Latour' },
      { name: 'Damien Logeart' },
      { name: 'Alain Cohen-Solal' },
      { name: 'Feriel Azibani' },
      { name: 'Jean-Guillaume Dillinger' },
      { name: 'Patrick Henry' },
      { name: 'Marie Robin' },
    ],
    submissions: [{ journalName: 'Canadian Journal of Cardiology', submittedAt: '2026-03-10', status: 'MAJOR_REVISIONS' }],
    notes:
      'Manuscript ID CJC-00258, R1 revision requested 10-mars 2026. Wording did not specify minor vs major, MAJOR_REVISIONS used per default rule.',
  },

  // #16 - Phenotypic Clustering of Allo-HSCT Recipients & CV Events - UNDER_REVIEW - corresp. Goncalves
  {
    title: 'Phenotypic Clustering of Allogeneic Hematopoietic Stem Cell Transplant Recipients Associated with Cardiovascular Events',
    articleStatus: 'UNDER_REVIEW',
    authors: [
      { name: 'Trecy Goncalves', isCorresponding: true },
      { name: 'Gregor Roncin' },
      { name: 'Benjamin Sibilia' },
      { name: 'Marie Robin' },
      { name: 'Florian Chevillon' },
      { name: 'Alienor Xhaard' },
      { name: 'Nathalie Dhedin' },
      { name: 'Matthieu Jestin' },
      { name: 'Regis Peffault de La Tour' },
      { name: 'Nicolas Boissel' },
      { name: 'Flore Sicre de Fontbrune' },
      { name: 'David Michonneau' },
      { name: 'Camilia Regragui' },
      { name: 'Rayane Hadjali' },
      { name: 'Damien Logeart' },
      { name: 'Alexandre Unger' },
      { name: 'Alain Cohen-Solal' },
      { name: 'Feriel Azibani' },
      { name: 'Jean-Guillaume Dillinger' },
      { name: 'Patrick Henry' },
      { name: 'Solenn Toupin' },
      { name: 'Theo Pezel' },
    ],
    submissions: [{ journalName: 'Circulation', submittedAt: '2026-04-17', status: 'UNDER_REVIEW' }],
    notes:
      'Manuscript ID 081056. Per validated audit decision #2, kept as an Article distinct from #15 (Post-Transplant Cyclophosphamide Cardiotoxicity) despite the overlapping author/topic area.',
  },

  // #18 - Nuclear Imaging Cardio-Rheumatology (EACVI-INFLAME) - UNDER_REVIEW - corresp. Pezel
  {
    title: 'Nuclear Imaging in Cardio-Rheumatology: Why a Global Initiative Like the EACVI-INFLAME Study Is Needed?',
    articleStatus: 'UNDER_REVIEW',
    authors: [
      { name: 'Aicha Kante' },
      { name: 'Marc R Dweck' },
      { name: 'Andreas A Giannopoulos' },
      { name: 'Giulia Elena Mandoli' },
      { name: 'Solenn Toupin' },
      { name: 'Sonia Borodzicz-Jazdzyk' },
      { name: 'Alessia Gimelli' },
      { name: 'Dominik C Benz' },
      { name: 'Nicolas Piriou' },
      { name: 'Thomas Eugene' },
      { name: 'Fabien Hyafil' },
      { name: 'Cloe Comarmond' },
      { name: 'Riemer H J A Slart' },
      { name: 'Paola Anna Erba' },
      { name: 'Maya H Buch' },
      { name: 'Theo Pezel', isCorresponding: true },
    ],
    submissions: [{ journalName: 'EANM Innovation', submittedAt: '2026-03-03', status: 'UNDER_REVIEW' }],
    notes: 'Manuscript ID EANMI-00017.',
  },

  // #19 - Carbon Cost of AI / Planetary Health - UNDER_REVIEW - corresp. Pezel (author list unavailable)
  {
    title: 'From Precision to Planetary Health: the Carbon Cost of AI in Multimodality Cardiovascular Imaging',
    articleStatus: 'UNDER_REVIEW',
    authors: [{ name: 'Theo Pezel', isCorresponding: true }],
    submissions: [{ journalName: 'European Heart Journal - Imaging Methods and Practice', submittedAt: '2026-04-01', status: 'UNDER_REVIEW' }],
    notes:
      'Manuscript ID EHJ-IMP-00125. Ordered author list not confirmed — only the corresponding author (Theo Pezel) is transcribed. Remaining co-authors are known only as an unordered pool (not transcribed pending confirmation of order): Alexandre Unger, Solenn Toupin, Camille Gersdorff, Aicha Kante, Julien Hudelo, Sofiane Sifaoui, Trecy Goncalves. Submission date only known to the month (avr 2026) — used the 1st as a placeholder.',
  },

  // #20 - Derivation/Validation CMR Risk Score prophylactic ICD, Ischemic CM - UNDER_REVIEW - corresp. Pontone
  {
    title: 'Derivation and internal Validation of A Novel Cardiac Magnetic Resonance Risk Score for Prophylactic Implantable-Cardioverter Defibrillator Therapy in Ischemic Cardiomyopathy',
    articleStatus: 'UNDER_REVIEW',
    authors: [
      { name: 'Alexandre Unger' },
      { name: 'Gianluca Pontone', isCorresponding: true },
    ],
    submissions: [{ journalName: 'European Heart Journal', submittedAt: '2026-02-09', status: 'UNDER_REVIEW' }],
    notes:
      'Manuscript ID EURHEARTJ-00644. This is a multicentre Italian study (PI Gianluca Pontone); the true corresponding author is Gianluca Pontone (probably last author), but he does not appear in the only names available to this transcription (first author Alexandre Unger). Per transcription rule 4, Alexandre Unger (first author) is set as a placeholder corresponding author instead. The full ~60-author list referenced in the audit source ("cf. JSON sous-agent") was not available for this transcription — only Alexandre Unger is transcribed pending that list.',
  },

  // #21 - Stress CMR ischemic burden & mortality, LV systolic dysfunction - UNDER_REVIEW - corresp. Garot (author list unavailable)
  {
    title: 'Stress CMR ischemic burden and long-term mortality in left ventricular systolic dysfunction: a multicenter registry study',
    articleStatus: 'UNDER_REVIEW',
    authors: [{ name: 'Jerome Garot', isCorresponding: true }],
    submissions: [{ journalName: 'European Heart Journal - Cardiovascular Imaging', submittedAt: '2026-01-25', status: 'UNDER_REVIEW' }],
    notes:
      'Only journal in the chain is EHJ-CVI: submitted 25-janv 2026, received a Major Revision decision, and was resubmitted around 11-avr 2026 (still under review) — represented as a single submission dated at the original 25-janv submission. Ordered author list unavailable; probable first author is Alexandre Pfeffer but this was not transcribed pending confirmation.',
  },

  // #22 - A Visual LGE Extent Threshold for Mortality, Ischemic CM - UNDER_REVIEW - corresp. Garot
  {
    title: 'A Visual LGE Extent Threshold for Mortality Risk Stratification in Ischemic Cardiomyopathy',
    articleStatus: 'UNDER_REVIEW',
    authors: [
      { name: 'Alexandre Unger' },
      { name: 'Suzanne Duhamel' },
      { name: 'Philippe Garot' },
      { name: 'Francesca Sanguineti' },
      { name: 'Myriam Akodad' },
      { name: 'Antoinette Neylon' },
      { name: 'Thomas Hovasse' },
      { name: 'Trecy Goncalves' },
      { name: 'Louis Perrard' },
      { name: 'Jeremy Florence' },
      { name: 'Aicha Kante' },
      { name: 'Julien Hudelo' },
      { name: 'Jean-Guillaume Dillinger' },
      { name: 'Antoine Bondue' },
      { name: 'Patrick Henry' },
      { name: 'Valerie Bousson' },
      { name: 'Solenn Toupin' },
      { name: 'Theo Pezel' },
      { name: 'Jerome Garot', isCorresponding: true },
    ],
    submissions: [
      { journalName: 'Circulation: Cardiovascular Imaging', submittedAt: '2026-02-12', status: 'REJECTED' },
      { journalName: 'Journal of Cardiovascular Magnetic Resonance', submittedAt: '2026-02-15', status: 'UNDER_REVIEW' },
    ],
    notes: 'Manuscript IDs: Circ CVI 019676, JCMR JOFCMR-00087.',
  },

  // #23 - Sex diff risk stratification, stress CMR, known/suspected CAD - UNDER_REVIEW - corresp. Garot (author list unavailable)
  {
    title: 'Sex differences in risk stratification by stress cardiovascular magnetic resonance imaging in patients with known or suspected CAD',
    articleStatus: 'UNDER_REVIEW',
    authors: [{ name: 'Jerome Garot', isCorresponding: true }],
    submissions: [{ journalName: 'European Heart Journal - Cardiovascular Imaging', submittedAt: '2026-05-02', status: 'UNDER_REVIEW' }],
    notes:
      'Ordered author list unavailable; probable first author is Giulia Vinco but this was not transcribed pending confirmation.',
  },

  // #24 - Clinical Importance of All LGE Characteristics AI Analysis: State-of-the-Art - PUBLISHED - corresp. Pezel
  {
    title: 'Clinical Importance of All the Characteristics of Late Gadolinium Enhancement from Acquisition to Expert and Artificial Intelligence Analysis: State-of-the-Art',
    articleStatus: 'PUBLISHED',
    authors: [{ name: 'Theo Pezel', isCorresponding: true }],
    submissions: [{ journalName: 'Journal of Cardiovascular Magnetic Resonance', submittedAt: '2026-06-09', status: 'ACCEPTED' }],
    notes:
      'Manuscript ID JOCMR_102764 (Rights & Access completed 9-juin 2026). Full author list not transcribed — the audit source notes it should be extracted from PubMed once published; only the corresponding author (Theo Pezel) is transcribed for now.',
  },

  // #26 - Optimal LVEF cut-off, end-stage HCM - rejected JCMR, no resubmission found - corresp. Hudelo
  {
    title: 'Optimal cut-off point of left ventricular ejection fraction for prediction of mortality in end-stage hypertrophic cardiomyopathy',
    articleStatus: 'TO_RESUBMIT',
    authors: [{ name: 'Julien Hudelo', isCorresponding: true }],
    submissions: [{ journalName: 'Journal of Cardiovascular Magnetic Resonance', submittedAt: '2026-02-17', status: 'REJECTED' }],
    notes:
      'Manuscript ID JOFCMR-00526, rejected 17-fev 2026 with no resubmission found in the audited mailbox. Per validated audit decision #1, kept as TO_RESUBMIT (rather than ABANDONED) so the rejection stays tracked. Full author list not available in the audit source — only the corresponding author (Julien Hudelo) is known.',
  },

  // #29 - The MULTIVALVE Study: Rationale, Objectives, Design - UNDER_REVIEW - corresp. Pezel
  {
    title: 'The MULTIVALVE Study: Rationale, Objectives, and Design of a French Registry on Multiple and Mixed Valvular Heart Disease',
    articleStatus: 'UNDER_REVIEW',
    authors: [
      { name: 'Gilles Soulat' },
      { name: 'Solenn Toupin' },
      { name: 'Yohann Bohbot' },
      { name: 'Charles Fauvel' },
      { name: 'Jerome Garot' },
      { name: 'Olivier Huttin' },
      { name: 'Anne Bernard' },
      { name: 'Loic Biere' },
      { name: 'Basile Mouhat' },
      { name: 'Julien Ternacle' },
      { name: 'Florent Le Ven' },
      { name: 'Gilles Barone-Rochette' },
      { name: 'Shamir Vally' },
      { name: 'Alexandre Altes' },
      { name: 'Catherine Sportouch' },
      { name: 'Quentin Delbaere' },
      { name: 'Thierry Le Tourneau' },
      { name: 'Sophie Ribeyrolles' },
      { name: 'Vincenzo Palermo' },
      { name: 'Claire Bouleti' },
      { name: 'Erwan Donal' },
      { name: 'Julien Dreyfus' },
      { name: 'Antonin Trimaille' },
      { name: 'Yoan Lavie Badie' },
      { name: 'Guillaume Clerfond' },
      { name: 'Romain Didier' },
      { name: 'Thiziri Si Moussi' },
      { name: 'Jean-Nicolas Dacher' },
      { name: 'Francois Pontana' },
      { name: 'Feriel Azibani' },
      { name: 'Alexandre Unger' },
      { name: 'Julien Magne' },
      { name: 'Bernard Iung' },
      { name: 'Eric Vicaut' },
      { name: 'Augustin Coisne' },
      { name: 'Theo Pezel', isCorresponding: true },
    ],
    submissions: [{ journalName: 'Archives of Cardiovascular Diseases', submittedAt: '2026-04-11', status: 'UNDER_REVIEW' }],
  },

  // #30 - Hemodynamic forces (non-contrast CMR) / Sarcoidosis - UNDER_REVIEW - corresp. Pezel
  {
    title: 'Hemodynamic forces: a novel non-contrast CMR parameter to detect early cardiac involvement in Sarcoidosis patients',
    articleStatus: 'UNDER_REVIEW',
    authors: [
      { name: 'Aicha Kante' },
      { name: 'Andreea Sorina Afana' },
      { name: 'Raphael Mirailles' },
      { name: 'Damien Sene' },
      { name: 'Solenn Toupin' },
      { name: 'Claire Baladi' },
      { name: 'Karine Champion' },
      { name: 'Valentine Pagis' },
      { name: 'William Bigot' },
      { name: 'Veronique Delcey' },
      { name: 'Amanda Lopes' },
      { name: 'Blanca Amador Borrero' },
      { name: 'Ruxandra Burlacu' },
      { name: 'Abdellatif Tazi' },
      { name: 'Bruno Crestani' },
      { name: 'Stephane Mouly' },
      { name: 'Paul-Jun Martial' },
      { name: 'Loic Biere' },
      { name: 'Julien Hudelo' },
      { name: 'Trecy Goncalves' },
      { name: 'Jean-Guillaume Dillinger' },
      { name: 'Patrick Henry' },
      { name: 'Valerie Bousson' },
      { name: 'Cloe Comarmond' },
      { name: 'Theo Pezel', isCorresponding: true },
    ],
    submissions: [{ journalName: 'Archives of Cardiovascular Diseases', submittedAt: '2026-04-11', status: 'UNDER_REVIEW' }],
  },
]
